In [45]:
## NumPy Basic
# Задача 1
import numpy as np
import math as m 
from numpy import linalg as lg
print(np.version.version)
print(np.show_config())

1.20.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/alina/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/alina/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/alina/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/alina/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/alina/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/alina/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/alina/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/alina/anaconda3\\Library\\include']
None


In [22]:
# Задача 2
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [23]:
# Задача 3
a = np.array([1, 2, 3, 4 , 5])
print("Ни один из элементов указанного массива не равен нулю: ", np.all(a))
a2 = np.array([1, 2, 3, 4 , 5, 0])
print("Ни один из элементов указанного массива не равен нулю: ", np.all(a2))

Ни один из элементов указанного массива не равен нулю:  True
Ни один из элементов указанного массива не равен нулю:  False


In [24]:
# Задача 4
a = np.array([1, 2, 3, 4 , 5])
print("Ни один из элементов указанного массива не равен нулю: ", np.any(a))
a2 = np.array([0, 0, 0, 0 , 0, 0])
print("Ни один из элементов указанного массива не равен нулю: ", np.any(a2))

Ни один из элементов указанного массива не равен нулю:  True
Ни один из элементов указанного массива не равен нулю:  False


In [29]:
# Задача 5
a = np.array([5, -4, np.nan, np.inf])
print("Проверка элементов заданного массива на конечность: ", np.isfinite(a))

Проверка элементов заданного массива на конечность:  [ True  True False False]


In [30]:
# Задача 6
a = np.array([5, -4, np.nan, np.inf])
print("Проверка элементов заданного массива на положительную или отрицательную бесконечность: ", np.isinf(a))

Проверка элементов заданного массива на положительную или отрицательную бесконечность:  [False False False  True]


In [32]:
# Задача 7
a = np.array([5, -4, np.nan, np.inf])
print("Проверка элементов заданного массива на NaN: ", np.isnan(a))

Проверка элементов заданного массива на NaN:  [False False  True False]


In [38]:
# Задача 8
a = np.array([5, -4, np.nan, np.inf, 1 + 2j, 5j, 3.14, 5.2])
print("Проверка элементов заданного массива на наличие комплексных чисел: ", np.iscomplex(a))
print("Проверка элементов заданного массива на наличие действительных чисел: ", np.iscomplex(a))
print("Проверка элемента заданного массива на наличие скалярного типа числа: ", np.isscalar([3.14]))
print("Проверка элемента заданного массива на наличие скалярного типа числа: ", np.isscalar(1 + 2j))

Проверка элементов заданного массива на наличие комплексных чисел:  [False False False False  True  True False False]
Проверка элементов заданного массива на наличие действительных чисел:  [False False False False  True  True False False]
Проверка элемента заданного массива на наличие скалярного типа числа:  False
Проверка элемента заданного массива на наличие скалярного типа числа:  True


In [40]:
# Задача 9
a1 = np.array([5e5, 1e-7, 4.000004e6])
a2 = np.array([5.00001e5, 1e-7, 4e6])
print("Являются ли два массива поэлементно равными в пределах допуска: ", np.allclose(a1, a2))

Являются ли два массива поэлементно равными в пределах допуска:  True


In [44]:
# Задача 10
a1 = np.array([5, -4, 1, 5.8])
a2 = np.array([0, 3, 3.14, -5.2])
print("Сравнение - больший: ", np.greater(a1, a2))
print("Сравнение - больший_эквивалент: ", np.greater_equal(a1, a2))
print("Сравнение - меньший: ", np.less(a1, a2))
print("Сравнение - меньший_эквивалент: ", np.less_equal(a1, a2))

Сравнение - больший:  [ True False False  True]
Сравнение - больший_эквивалент:  [ True False False  True]
Сравнение - меньший:  [False  True  True False]
Сравнение - меньший_эквивалент:  [False  True  True False]


In [3]:
##NumPy массивы
# Задача 9
a = np.ones((3,3))  #заполняем единицами 3 на 3
a = np.pad(a, pad_width=1, mode='constant', constant_values=0) #pad_with - количество значений, добавленных к краю каждой оси
print(a)                                                       #constant - заполнение происходит с постоянным значением

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [9]:
# Задача 11
a = list(range(1, 9))
print(np.asarray(a)) #преобразовать список в массив
b = ([8, 4, 6], [1, 2, 3]) 
print(np.asarray(b)) #кортеж в массив

[1 2 3 4 5 6 7 8]
[[8 4 6]
 [1 2 3]]


In [15]:
# Задача 13
a = np.empty((4,3)) #(пустой) Массив неициированных (случайных) значений, указанной формы, типа и порядка
print(a)
b = np.full((3,3),8) #Полный массив
print(b)

[[1.09409715e-311 2.47032823e-322 0.00000000e+000]
 [0.00000000e+000 7.56587583e-307 1.33664410e+160]
 [6.81637749e-091 1.45138931e+165 4.31924849e-038]
 [8.84374829e+165 3.99910963e+252 4.93432906e+257]]
[[8 8 8]
 [8 8 8]
 [8 8 8]]


In [18]:
# Задача 15
a = np.array([1.00000000 + 0.j, 0.70710678 + 0.70710678j])
print("Действительные части массива комплексных чисел: ", a.real)
print("Мнимые части массива комплексных чисел: ", a.imag)

Действительные части массива комплексных чисел:  [1.         0.70710678]
Мнимые части массива комплексных чисел:  [0.         0.70710678]


In [20]:
# Задача 17
array1 = np.array([0, 1, 2, 3, 5])
array2 = np.arange(0, 10, 2)
print(np.in1d(array1, array2)) #Присутствует ли каждый элемент одномерного массива во втором массиве

[ True False  True False False]


In [22]:
# Задача 19
a = np.array([10, 10, 20, 20, 30, 30])
print("Уникальные элементы массива: ", np.unique(a))

Уникальные элементы массива:  [10 20 30]


In [24]:
# Задача 21
array1 = ([0, 10, 20, 40, 60, 80])
array2 = ([10, 30, 40, 50, 70])
print("Уникальные значения, которые есть только в одном (а не в обоих) входных массивах: ", np.setxor1d(array1, array2))

Уникальные значения, которые есть только в одном (а не в обоих) входных массивах:  [ 0 20 30 50 60 70 80]


In [26]:
# Задача 23
#Проверить все ли значения в массиве- True(0 - False)
print(np.all([[True,False],[True,True]]))
print(np.all([[True,True],[True,True]]))
print(np.all([10, 20, 0, -50]))
print(np.all([10, 20, -50]))

False
True
False
True


In [28]:
# Задача 25
a = np.array([1, 2, 3, 4])
print(np.tile(a, 2)) #Массив повторился 2 раза

[1 2 3 4 1 2 3 4]


In [32]:
# Задача 27
a = np.array([1, 2, 3, 4, 5, 6])
print(np.argmax(a)) #Максимальное значение
print(np.argmin(a)) #Минимальное значение

5
0


In [44]:
## Numpy Линейная алгебра
# Задача 1
a1 = [[1, 0], [0, 1]]
a2 = [[1, 2], [3, 4]]
print("Результат умножения 2х матриц: ")
print(np.dot(a1, a2))

Результат умножения 2х матриц: 
[[1 2]
 [3 4]]


In [46]:
# Задача 4
a = np.array([[1, 0], [1, 2]])
print("Определитель квадратного массива: ", np.linalg.det(a)) #двумерный массив, количество строк и столбцов в котором одинаково

Определитель:  2.0


In [49]:
# Задача 11
a = np.array([[1,2,5],[3,4,6],[8,7,9]])
print("Определитель массива: ", np.linalg.det(a))

Определитель массива:  -18.999999999999996


In [52]:
# Задача 12
a = np.array([[1,2,5],[3,4,6],[8,7,9]])
print("Обратная матрица: ")
print(np.linalg.inv(a))

Обратная матрица: 
[[ 0.31578947 -0.89473684  0.42105263]
 [-1.10526316  1.63157895 -0.47368421]
 [ 0.57894737 -0.47368421  0.10526316]]


In [54]:
# Задача 2
a1 = [[1, 0], [0, 1]]
a2 = [[1, 2], [3, 4]]
print("Внешнее произведение двух заданных векторов: ")
print(np.outer(a1, a2))

Внешнее произведение двух заданных векторов: 
[[1 2 3 4]
 [0 0 0 0]
 [0 0 0 0]
 [1 2 3 4]]


In [57]:
# Задача 3
a1 = [[1, 0], [0, 1]]
a2 = [[1, 2], [3, 4]]
print("Перекрестное произведение двух заданных векторов: ")
print("(a1,a2)", np.cross(a1, a2))
print("(a2,a1)", np.cross(a2, a1))

Перекрестное произведение двух заданных векторов: 
(a1,a2) [ 2 -3]
(a2,a1) [-2  3]


In [59]:
# Задача 15
a = [[0, 1, 2],
    [3, 4, 5]]
print("Сумма диагонального элемента данного массива: ", np.trace(a))

Сумма диагонального элемента данного массива:  4
