**18 Основы Numpy. Часть 1 **

Пример создания массива при помощи модуля array стандартной библиотеки Python:

In [ ]:
import array
a = array.array('i', [1,2,3,4,5])

"""Создаем новый массив b на основе а"""

b = array.array(a.typecode, (2*x for x in a))
# array.typecode - TypeCode символ, использованный при создании массива
print(a)
print(b)

array('i', [1, 2, 3, 4, 5])
array('i', [2, 4, 6, 8, 10])


In [ ]:
import array
a = array.array('f', [1,2,3,4,5])

"""Создаем новый массив b на основе а"""

b = array.array(a.typecode, (2*x for x in a))
# array.typecode - TypeCode символ, использованный при создании массива
print(a)
print(b)

array('f', [1.0, 2.0, 3.0, 4.0, 5.0])
array('f', [2.0, 4.0, 6.0, 8.0, 10.0])


In [ ]:
import numpy as np

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(a.shape) # определяем форму массива

(2, 3)


In [ ]:
print(a.reshape(6, 1)) # преобразуем формат 2 строки, 3 столбца: (2, 3) в (6, 1) - 6 строк и 1 столбец

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [ ]:
print(np.zeros((3, 2), dtype=int)) #np.ones - единицы

[[0 0]
 [0 0]
 [0 0]]


In [ ]:
print(np.zeros((3, 2)))

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
#Функция eye(N, M, k) создаёт двумерный массив из нулей, где N строк, M=N (по умолчанию) столбцов и единиц по диагонали для k=0,  
#для k = 1 - со сдвигом диагонали с единицами вверх и для k=-1 - со сдвигом диагонали с единицами вниз.
a = np.eye(4, 4, k=0) 
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#Функция full(shape, fill_value) создает массив заданного формата и из указанных одинаковых значений.
a = np.full((2, 2), 5)
print(a)

[[5 5]
 [5 5]]


Задача 1

In [ ]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
print("Массив:\n", a)

Массив:
 [[1 2 3]
 [4 5 6]]


Задача 2

In [ ]:
import numpy as np
print(np.eye(4, 4, k=0, dtype=int))

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


Задача 3

In [ ]:
import numpy as np
print(np.zeros((8), dtype=int))

Задача 4

In [ ]:
import numpy as np
print(np.zeros((8, 1), dtype=int))

Задача 5

In [ ]:
import numpy as np
print(np.full((2, 2), 5, dtype=float))

[[5. 5.]
 [5. 5.]]


Задача 6

In [ ]:
print("%.2f"% np.random.sample())
print(np.random.sample(3))
print(np.random.sample((2, 3)))


0.75
[0.12081842 0.90148076 0.00449469]
[[0.68783819 0.40142918 0.72187321]
 [0.15498645 0.08014955 0.89309226]]


Задача 7

In [ ]:
import numpy as np
import random 

def random_perest(a):
  i, j = random.sample(range(0, len(a)), 2)
  k = a[i]
  a[i] = a[j]
  a[j] = k
  return a

In [ ]:
a = [1, 2, 3, 4, 5, 6, 7, 8]
a = random_perest(a)
a = random_perest(a)
a = random_perest(a)
print(a)

[3, 2, 1, 5, 8, 6, 7, 4]


In [ ]:
#Создать матрицу с 0 внутри и 1 на границах
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
Z = np.ones((3,3))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


Задача 8

In [ ]:
import numpy as np
Z = np.zeros((5,5),dtype = int)
Z[1:-1,1:-1] = 1
print(Z)

[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]


In [ ]:
import numpy as np
import random
a = np.random.random_integers(1, 10, size=(3, 3))
print(a)
print("Минимум: ", a.min(axis=None)) 
print("Максимум: ", a.max(axis=None))
print("Среднее арифметическое: ", a.mean(axis=None)) 
print("Стандартное отклонение: ", a.std(axis=None)) 
print("Индекс минимального значения: ", a.argmin(axis=None))
print("Индекс максимального значения: ", a.argmax(axis=None))

[[ 4  6  2]
 [ 1  2  4]
 [10  3  8]]
Минимум:  1
Максимум:  10
Среднее арифметическое:  4.444444444444445
Стандартное отклонение:  2.8327886186626583
Индекс минимального значения:  3
Индекс максимального значения:  6


<ipython-input-47-d4d7f8bc636e>:3: DeprecationWarning: This function is deprecated. Please call randint(1, 10 + 1) instead
  a = np.random.random_integers(1, 10, size=(3, 3))


**19 Основы Numpy. Часть 2**

Пример кода для определения количества осей тензора:

In [ ]:
import numpy as np

x = np.array(1) 
print(x.ndim)
y = np.array([1, 2, 3])
print(y.ndim)
z = np.array([[1, 2, 3], [4,5,6]])
print(z.ndim)

0
1
2


In [ ]:
import numpy as np
x = np.array(200) 
print(x.ndim)

0


In [ ]:
import numpy as np
y = np.array([1, 2, 3, 4, 5, 6])
print(y.ndim)

1


In [ ]:
import numpy as np
x = np.array([[1, 2, 3], [4,5,6], [4,5,6], [4,5,6]])
print(x.ndim)

2


Пример кода умножения матрицы на число и сложения матриц:

In [ ]:
a = np.eye(3, 4, 0, int) # матрица из 3-х строк и 4-х столбцов из 0, с 1 - по главной диагонали
b = np.eye(3, 4, 1, int) # матрица из 3-х строк и 4-х столбцов из 0, с 1 - по верхней диагонали
c = 2*a + b 
print(c)

[[2 1 0 0]
 [0 2 1 0]
 [0 0 2 1]]


Пример кода для вычисления скалярного произведения векторов:

In [ ]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
print("Скалярное произведение векторов a = {} и b = {}:".format(a, b))
print(np.dot(a, b))
print("Скалярное произведение:", a.dot(b)) # другой формат функции dot

Скалярное произведение векторов a = [1 2 3] и b = [4 5 6]:
32
Скалярное произведение: 32


In [ ]:
a = np.array([4, 1, 8])
b = np.array([4, 5, 6])
print(np.dot(a, b))

69


Пример кода векторного произведения двух векторов:

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([5, 6, 7])
c = np.cross(a, b)
print("Вектор а =", a)
print("\nВектор b =", b)
print("\nВекторное произведение [a x b] =", c)

Вектор а = [1 2 3]

Вектор b = [5 6 7]

Векторное произведение [a x b] = [-4  8 -4]


Пример кода произведения матриц:

In [ ]:
import numpy as np

a = np.array([[1,2], [3,4]])
print( "\nМассив a:\n", a)

b = np.array([[1,2], [3,4]])
print( "\nМассив b:\n", b)

print( """\nПроизведение двух массивов а и b:
           1 - (1,2)*(1,3) = 1*1 + 2*3 = 7
           2 - (1,2)*(2,4) = 1*2 + 2*4 = 10
           3 - (3,4)*(1,3) = 3*1 + 4*3 = 15
           4 - (3,4)*(2,4) = 3*2 + 4*4 = 22""")
print(a.dot(b))


Массив a:
 [[1 2]
 [3 4]]

Массив b:
 [[1 2]
 [3 4]]

Произведение двух массивов а и b:
           1 - (1,2)*(1,3) = 1*1 + 2*3 = 7
           2 - (1,2)*(2,4) = 1*2 + 2*4 = 10
           3 - (3,4)*(1,3) = 3*1 + 4*3 = 15
           4 - (3,4)*(2,4) = 3*2 + 4*4 = 22
[[ 7 10]
 [15 22]]


**Задача**

Найдите произведение двух матриц.

Первая матрица состоит из единиц, формат массива (5, 3); вторая матрица состоит из семерок, формат массива (3, 2). 

Сделайте вывод каждой матрицы и их произведения.

Для корректной проверки кода, вывод текста и соответствующей ему матрицы реализуйте в  операторе print для каждой матрицы. Для переноса на следующую строку используйте \n.

In [ ]:
import numpy as np
a = np.ones((5,3), dtype = float)
b = np.full((3,2), 7, dtype = int)
print("\nПервая матрица:\n", a)
print("\nВторая матрица:\n", b)
print("\nПроизведение матриц:\n", np.dot(a, b))


Первая матрица:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Вторая матрица:
 [[7 7]
 [7 7]
 [7 7]]

Произведение матриц:
 [[21. 21.]
 [21. 21.]
 [21. 21.]
 [21. 21.]
 [21. 21.]]


**20 Представление данных для нейронных сетей. Часть 1**

*Ключевые атрибуты тензоров*

Тензор определяется тремя ключевыми атрибутами:

1-Количество осей (ранг) — например, трехмерный тензор имеет три оси, а матрица — две. В библиотеках для Python, таких как Numpy, этот атрибут тензоров имеет имя ndim .

2-Форма — кортеж целых чисел, описывающих количество измерений на каждой оси тензора. Например, матрица в предыдущем примере имеет форму (3, 5) , а трехмерный тензор имеет форму (3, 3, 5) . Вектор имеет форму с единственным элементом, например (5,) , тогда как скаляр имеет пустую форму (). В NumPy форма хранится в атрибуте shape.

3-Тип данных (обычно в библиотеках для Python ему дается имя dtype ) — это тип данных, содержащихся в тензоре; например, тензор может иметь тип float32 , uint8 , float64 и др. В редких случаях можно встретить тензоры типа char. Обратите внимание, что в Numpy (и в большинстве других библиотек) отсутствуют строковые тензоры, потому что тензоры хранятся в заранее выделенных, непрерывных сегментах памяти и строки, будучи сущностями с изменяющейся длиной, препятствуют использованию такой реализации. В NumPy форма хранится в атрибуте dtype.

*Размерность массива может быть увеличена при использовании константы newaxis или с помощью функции expand_dims() *